### ISSUE TITLE
Just an idiomatic thought.

### ISSUE THREAD

**Issue by freman** [bcicen/grmon#1]
My first impulse (right after, I could have really used this 3 weeks ago lol) is to "Yuck dep" but instead...

if you put cli in cmd/grmon

One could simply

```
go get github.com/bcicen/grmon
go install github.com/bcicen/grmon/cmd/grmon
```

No make or dep required (turns out I don't have dep installed, and I'm happy with that state of affairs 😁 )

You could still have a makefile and use dep, but the cmd/executable is more idiomatic

**Comment by SimonRichardson** [comment]
Alternatively you could just store your vendor directory.

**Comment by freman** [comment]
Aint no-one wanna pull everyone's damn vender directory 👅

**Comment by bcicen** [comment]
As `grmon` uses a forked/modified version of the upstream termui library, vendored dependencies are used to ensure consistent builds.

The tool is now installable via a simple `go get`; though, `Gopkg` files will remain for development and general good practice
