### ISSUE TITLE
Why the github.com/bcicen/grmon import?

### ISSUE THREAD

**Issue by erikdubbelboer** [bcicen/grmon#2]
Why can't grmon not just parse the output of `/debug/pprof/goroutine?debug=1`?

This would make things a lot easier as the program you want to monitor doesn't have to add another dependency.

**Comment by bcicen** [comment]
If any supplemental data (not already in pprof profile) is used going forward, the import would be still be needed; however, yes, in its current state parsing can just as well be moved into the client.

I will likely make this change in the next iteration. Thanks for the feedback!

**Comment by jhillyerd** [comment]
I was thinking of opening an issue to say that grmon doesn't work for apps that don't use the http.DefaultServeMux.  However, switching to /debug/pprof ought to solve that as well.

**Comment by bcicen** [comment]
`grmon` now reads directly from `/debug/pprof` of the target by default.

An (optional) [agent](https://github.com/bcicen/grmon/blob/master/agent/main.go) is still included as well to allow for extended profiling data in the future.
