### ISSUE TITLE
Under macos iterm2 there is no highlight on selecting goroutine.

### ISSUE THREAD

**Issue by FrontMage** [bcicen/grmon#3]
Using macos iterm2 with grmon latest, but there is no hightlighting for selected goroutine.

Besides that everything works great, and I managed to find a goroutine leak after using grmon for 3 minutes.

Great tool!

**Comment by bcicen** [comment]
Thanks for the feedback! Are you not seeing a cursor to the left of the selected row when `grmon` is paused(`p`)? Cursor is disabled while unpaused / automatically refreshing.

**Comment by FrontMage** [comment]
Oh, I thought the cursor is always displayed, turns out I need to pause.

After pause there is indeed a cursor, sorry for the false alarm, I didn't quite finish the README.
