### ISSUE TITLE
error occured when make install

### ISSUE THREAD

**Issue by barryz** [bcicen/grmon#4]
Platform: mac os 
Terminal: Iterm2
Error Msg: 
```bash
% make install                                                                    
make build
dep ensure
make[1]: dep: No such file or directory
make[1]: *** [build] Error 1
make: *** [install] Error 2
```

**Comment by bcicen** [comment]
`grmon` requires [dep](https://github.com/golang/dep) to ensure you get the correct forked version of upstream libraries at build time.

on mac, you can install with brew ` brew install dep` or simply `go get -u github.com/golang/dep/cmd/dep`

**Comment by barryz** [comment]
thanks,  should add this to README ，I think..
