### ISSUE TITLE
movement keys aren't working

### ISSUE THREAD

**Issue by gholt** [bcicen/grmon#6]
Possibly a terminal mismatch issue, not sure yet, but the movement keys aren't working for me. I can hit 't' and get the trace for the item, but I can't really see which item I've selected.

Neat tool!

**Comment by bcicen** [comment]
Are you not seeing a cursor to the left of the selected row when grmon is paused(p)? Cursor is disabled while unpaused / automatically refreshing.

**Comment by gholt** [comment]
Ah, got it. The paused part being required wasn't readily apparent to me. :)  Works okay now. When running, hitting the movement keys sometimes emits some newlines here and there. And maybe a movement key while running should automatically pause. Anyway, works as intended so I'm closing the issue. Thanks!

**Comment by bcicen** [comment]
`t` showing the trace window when not paused actually is a bug; fixed pushed in the [latest commit](https://github.com/bcicen/grmon/commit/226df05068906657f1c96c80d8452760e242923d). This should resolve some other weird key behavior as well.

Thanks for the feedback!
